stages:
  - test

# Use the official Node.js image from Docker Hub.
image: node:18

# Define cache to speed up subsequent jobs by caching the node_modules folder.
cache:
  paths:
    - frontend/node_modules/

before_script:
  # Navigate to the frontend directory and install dependencies.
  - cd frontend
  - npm install

test:
  stage: test
  script:
    # Run the frontend tests.
    - npm run test -- --ci --reporters=default --reporters=jest-junit
  tags:
    - shared-runner  # Use the appropriate runner tag
  artifacts:
    # Save the test results as artifacts.
    when: always
    reports:
      junit: junit.xml