image: node:18

stages:
  # - setup
  # - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

# setup:
#   stage: setup
#   tags:
#     - shared-runner
#   script:
#     # Install backend and frontend dependencies
#     - npm run setup

# build:
#   stage: build
#   tags:
#     - shared-runner
#   script:
#     # Build both backend and frontend
#     - CI='' npm run build
#   artifacts:
#     paths:
#       - backend/dist/  # Backend build files
#       - backend/build/  # Frontend build files moved to backend

deploy:
  stage: deploy
  tags:
    - shared-runner
  script:
    - echo "Deploying to Heroku"
    # Install Heroku CLI
    - curl https://cli-assets.heroku.com/install.sh | sh
    # Add Heroku remote
    - heroku git:remote -a scribe-mark
    # Set Git to use the HEROKU_API_KEY environment variable for authentication
    - git remote set-url heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/scribe-mark.git
    - git fetch --all  # Fetch all branches
    - git checkout dev-heroku-deploy  # Checkout the correct branch
    # Push from 'dev-heroku-deploy' branch to Heroku's 'main' branch
    - git push heroku dev-heroku-deploy:main
  only:
    - dev-heroku-deploy  # Make sure the pipeline only runs when 'dev-heroku-deploy' is updated
