image: node:18

stages:
  - setup
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

setup:
  stage: setup
  script:
    # Install backend and frontend dependencies
    - npm run setup

build:
  stage: build
  script:
    # Build both backend and frontend
    - npm run build
  artifacts:
    paths:
      - backend/dist/  # Backend build files
      - backend/build/  # Frontend build files moved to backend

deploy:
  stage: deploy
  script:
    - echo "Deploying to Heroku"
    # Install Heroku CLI
    - curl https://cli-assets.heroku.com/install.sh | sh
    # Add Heroku remote
    - heroku git:remote -a scribe-mark
    # Push from 'dev-heroku-deploy' branch to Heroku's 'main' branch
    - git push heroku dev-heroku-deploy:main
  only:
    - dev-heroku-deploy  # Make sure the pipeline only runs when 'dev-heroku-deploy' is updated
