stages:
  - test

image: node:18

cache:
  paths:
    - frontend/node_modules/

before_script:
  - cd frontend
  - npm install

test:
  stage: test
  script:
    - npm run test -- --ci --reporters=default --reporters=jest-junit
  tags:
    - shared-runner